fix QF_BV.hpp(234): error C2440: 'return': cannot convert from 'const metaSMT::logic::QF_BV::QF_BV<Expr>' to 'metaSMT::logic::QF_BV::QF_BV<Expr>' [C:\projects\metaSMT\build\tests\direct_Z3.vcxproj]