Revert "fix error C2664: 'bool metaSMT::result_wrapper::as_integer<Integer>::operator ()(bool) const': cannot convert argument 1 from 'const T5' to 'const boost::dynamic_bitset<unsigned long,std::allocator<Block>>"
This reverts commit d3ce6ac88a514e8a400daa675f6b664165436fc3.